### ISSUE TITLE
What's your feedback about this stack?

### ISSUE THREAD

**Issue by mrpeu** [yushimatenjin/playcanvas-sveltekit-tauri#1]
I'm curious about investing into Playcanvas with Svelte. Were you happy with your project?

**Comment by yushimatenjin** [comment]
Hello, I was able to use it well in its current state because I was familiar with PlayCanvas.
Now, it seems that the ESM support (Engine 2.0) update for PlayCanvas is in progress, so it might be good to look into this as well.
https://github.com/playcanvas/engine/issues/6666

**Comment by mrpeu** [comment]
Awesome, thanks 👍
